# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          yarn install
          yarn build
          yarn test          
